name: Sourcegraph Go LSIF Indexer
description: Generate LSIF data from Go source code
author: Sourcegraph
branding:
  icon: code
  color: purple

inputs:
  verbose:
    description: Set to true to log indexer progress
    required: false
    default: ''

runs:
  using: docker
  image: Dockerfile
  environment:
    - VERBOSE=${{ input.verbose }}
