name: Sourcegraph Go LSIF Indexer
description: Generate LSIF data from Go source code
author: Sourcegraph
branding:
  icon: code
  color: purple

inputs:
  version:
    description: Version of lsif-go to use.
    required: true
  file:
    description: The output filename (relative to the repository root).
    default: dump.lsif
  project_root: 
    description: The root of the project (where go.mod is located).
    default: .

runs:
  using: docker
  image: sourcegraph/lsif-go:${{ inputs.version }}
  args:
    - --out=${{ inputs.file }}
    - --repositoryRoot=${{ inputs.project_root }}
